// Code generated by mockery. DO NOT EDIT.

package user

import mock "github.com/stretchr/testify/mock"

// MockUser is an autogenerated mock type for the User type
type MockUser struct {
	mock.Mock
}

type MockUser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUser) EXPECT() *MockUser_Expecter {
	return &MockUser_Expecter{mock: &_m.Mock}
}

// ID provides a mock function with given fields:
func (_m *MockUser) ID() UserID {
	ret := _m.Called()

	var r0 UserID
	if rf, ok := ret.Get(0).(func() UserID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(UserID)
	}

	return r0
}

// MockUser_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockUser_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockUser_Expecter) ID() *MockUser_ID_Call {
	return &MockUser_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockUser_ID_Call) Run(run func()) *MockUser_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUser_ID_Call) Return(_a0 UserID) *MockUser_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUser_ID_Call) RunAndReturn(run func() UserID) *MockUser_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with given fields:
func (_m *MockUser) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockUser_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockUser_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockUser_Expecter) Name() *MockUser_Name_Call {
	return &MockUser_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockUser_Name_Call) Run(run func()) *MockUser_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUser_Name_Call) Return(_a0 string) *MockUser_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUser_Name_Call) RunAndReturn(run func() string) *MockUser_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUser creates a new instance of MockUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUser {
	mock := &MockUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
