name: format & lint check
on:
  push:
    branches:
      - main
jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Format Check
        run: make fmt-check
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install golangci-lint
        run: > # https://golangci-lint.run/usage/install/#other-ci
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.54.2
          echo "./bin" >> $GITHUB_PATH
      - name: Lint Check
        run: make golangci-lint

