name: Workflow for push to main
on:
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - uses: actions/cache@v3
        id: go_env_cache
        with:
          path: |
            ~/go/pkg
            ~/go/bin
            ~/.cache/go-build
          key: go-env-${{ hashFiles('**/go.sum') }}-${{ hashFiles('Makefile') }}
      - name: Install
        if: steps.go_env_cache.outputs.cache-hit != 'true'
        run: make install
  check-format:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: go_env_cache
        with:
          path: |
            ~/go/pkg
            ~/go/bin
            ~/.cache/go-build
          key: go-env-${{ hashFiles('**/go.sum') }}-${{ hashFiles('Makefile') }}
      - name: Install
        if: steps.go_env_cache.outputs.cache-hit != 'true'
        run: make install
      - name: Format check
        run: make fmt-check
  check-lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: go_env_cache
        with:
          path: |
            ~/go/pkg
            ~/go/bin
            ~/.cache/go-build
          key: go-env-${{ hashFiles('**/go.sum') }}-${{ hashFiles('Makefile') }}
      - name: Install
        if: steps.go_env_cache.outputs.cache-hit != 'true'
        run: make install
      - name: Lint check
        run: make golangci-lint
  check-auto-gen:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: go_env_cache
        with:
          path: |
            ~/go/pkg
            ~/go/bin
            ~/.cache/go-build
          key: go-env-${{ hashFiles('**/go.sum') }}-${{ hashFiles('Makefile') }}
      - name: Install
        if: steps.go_env_cache.outputs.cache-hit != 'true'
        run: make install
      - name: Generation
        run: make tests
      - name: Check diff
        run: git add . && git diff --cached --quiet
      - name: Show diff if failure
        if: ${{ failure() }}
        run: git diff --cached
  test:
    needs: [check-format, check-lint, check-auto-gen]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: go_env_cache
        with:
          path: |
            ~/go/pkg
            ~/go/bin
            ~/.cache/go-build
          key: go-env-${{ hashFiles('**/go.sum') }}-${{ hashFiles('Makefile') }}
      - name: Install
        if: steps.go_env_cache.outputs.cache-hit != 'true'
        run: make install
      - name: Run test
        run: make run-te
